import colorama
from colorama import Fore, Back, Style

# Initialize colorama (required for Windows)
colorama.init(autoreset=True)

def code(text):
    """Format text as code with color"""
    return f"{Fore.CYAN}{text}{Style.RESET_ALL}"

def keyword(text):
    """Format text as Python keyword with color"""
    return f"{Fore.BLUE}{text}{Style.RESET_ALL}"

def string(text):
    """Format text as string with color"""
    return f"{Fore.GREEN}{text}{Style.RESET_ALL}"

def comment(text):
    """Format text as comment with color"""
    return f"{Fore.YELLOW}{text}{Style.RESET_ALL}"

def heading(text):
    """Format text as heading with color"""
    return f"{Fore.MAGENTA}{Style.BRIGHT}{text}{Style.RESET_ALL}"

def display_header():
    print("\n" + "=" * 70)
    print(f"{Fore.MAGENTA}{Style.BRIGHT}{'ADVANCED PYTHON CHEAT SHEET'.center(70)}{Style.RESET_ALL}")
    print("=" * 70)

def display_main_menu():
    print("\nPlease select from the following options:\n")
    print(f"{Fore.GREEN}[1] API Calls and Requests{Style.RESET_ALL}")
    print(f"{Fore.GREEN}[2] Multithreading and Multiprocessing{Style.RESET_ALL}")
    print(f"{Fore.GREEN}[3] Working with JSON{Style.RESET_ALL}")
    print(f"{Fore.GREEN}[4] Working with CSV Files{Style.RESET_ALL}")
    print(f"{Fore.GREEN}[5] Working with PDFs{Style.RESET_ALL}")
    print(f"{Fore.GREEN}[6] Web Scraping{Style.RESET_ALL}")
    print(f"{Fore.GREEN}[7] Data Analysis with Pandas{Style.RESET_ALL}")
    print(f"{Fore.GREEN}[8] Advanced Python Concepts{Style.RESET_ALL}")
    print(f"{Fore.GREEN}[9] Help{Style.RESET_ALL}")
    print(f"{Fore.GREEN}[0] Exit{Style.RESET_ALL}")

def display_continue_menu():
    print(f"\n{Fore.GREEN}[1] Continue{Style.RESET_ALL}")
    print(f"{Fore.GREEN}[0] Main Menu{Style.RESET_ALL}")
    choice = input("\nEnter your choice: ")
    return choice

def display_help():
    print("\n" + "=" * 70)
    print(heading("HELP".center(70)))
    print("=" * 70)
    print("\nThis is an advanced Python cheat sheet program.")
    print("Select a topic number to view information about advanced Python topics.")
    print("After viewing a topic, you can continue for more information")
    print("or return to the main menu.")
    print("Select '0' to exit the program.")
    print("\nThe cheat sheet includes color coding:")
    print(f"{Fore.CYAN}Blue text{Style.RESET_ALL} indicates Python code")
    print(f"{Fore.BLUE}Dark blue{Style.RESET_ALL} indicates Python keywords")
    print(f"{Fore.GREEN}Green text{Style.RESET_ALL} indicates strings")
    print(f"{Fore.YELLOW}Yellow text{Style.RESET_ALL} indicates comments")
    print(f"{Fore.MAGENTA}Magenta text{Style.RESET_ALL} indicates headings")

def display_api_calls():
    print("\n" + "=" * 70)
    print(heading("API CALLS AND REQUESTS".center(70)))
    print("=" * 70)
    
    print("\n" + heading("Making HTTP Requests with Requests Library:"))
    print(comment("# Installing the requests library"))
    print(code("pip install requests"))
    print("\n" + comment("# Basic GET request"))
    print(code("import requests"))
    print(code("response = requests.get(") + string("'https://api.example.com/data'") + code(")"))
    print(code("print(response.status_code)  ") + comment("# 200 means success"))
    print(code("print(response.text)         ") + comment("# Response body as text"))
    print(code("data = response.json()       ") + comment("# Parse JSON response"))
    
    choice = display_continue_menu()
    if choice == "1":
        print("\n" + heading("Request Parameters and Headers:"))
        print(comment("# GET request with parameters"))
        print(code("params = {") + string("'key'") + code(": ") + string("'value'") + code(", ") + string("'query'") + code(": ") + string("'python'") + code("}"))
        print(code("response = requests.get(") + string("'https://api.example.com/search'") + code(", params=params)"))
        print("\n" + comment("# Adding headers to a request"))
        print(code("headers = {"))
        print(code("    ") + string("'User-Agent'") + code(": ") + string("'Python Script'") + code(","))
        print(code("    ") + string("'Authorization'") + code(": ") + string("'Bearer token123'") + code(","))
        print(code("    ") + string("'Content-Type'") + code(": ") + string("'application/json'"))
        print(code("}"))
        print(code("response = requests.get(") + string("'https://api.example.com/data'") + code(", headers=headers)"))
        
        choice = display_continue_menu()
        if choice == "1":
            print("\n" + heading("POST, PUT, and DELETE Requests:"))
            print(comment("# POST request with JSON data"))
            print(code("data = {") + string("'name'") + code(": ") + string("'John Doe'") + code(", ") + string("'email'") + code(": ") + string("'john@example.com'") + code("}"))
            print(code("response = requests.post(") + string("'https://api.example.com/users'") + code(", json=data)"))
            print("\n" + comment("# PUT request to update data"))
            print(code("response = requests.put(") + string("'https://api.example.com/users/123'") + code(", json=data)"))
            print("\n" + comment("# DELETE request to remove data"))
            print(code("response = requests.delete(") + string("'https://api.example.com/users/123'") + code(")"))
            print("\n" + heading("Authentication:"))
            print(comment("# Basic authentication"))
            print(code("response = requests.get(") + string("'https://api.example.com/secure'") + code(", auth=(") + string("'username'") + code(", ") + string("'password'") + code("))"))
            print("\n" + comment("# API key authentication (via query parameter)"))
            print(code("params = {") + string("'api_key'") + code(": ") + string("'your_api_key_here'") + code("}"))
            print(code("response = requests.get(") + string("'https://api.example.com/data'") + code(", params=params)"))
            
            choice = display_continue_menu()
            if choice == "1":
                print("\n" + heading("Handling Responses and Errors:"))
                print(code("response = requests.get(") + string("'https://api.example.com/data'") + code(")"))
                print(code("try:"))
                print(code("    response.raise_for_status()  ") + comment("# Raises an HTTPError for bad responses"))
                print(code("    data = response.json()"))
                print(code("except requests.exceptions.HTTPError as err:"))
                print(code("    print(f") + string("'HTTP error occurred: {err}'") + code(")"))
                print(code("except requests.exceptions.ConnectionError:"))
                print(code("    print(") + string("'Connection error occurred'") + code(")"))
                print(code("except requests.exceptions.Timeout:"))
                print(code("    print(") + string("'Request timed out'") + code(")"))
                print(code("except requests.exceptions.JSONDecodeError:"))
                print(code("    print(") + string("'Response is not valid JSON'") + code(")"))
                print("\n" + heading("Using Sessions:"))
                print(comment("# Sessions maintain cookies and connection across requests"))
                print(code("session = requests.Session()"))
                print(code("session.headers.update({") + string("'User-Agent'") + code(": ") + string("'Python Script'") + code("})"))
                print(code("response1 = session.get(") + string("'https://api.example.com/page1'") + code(")"))
                print(code("response2 = session.get(") + string("'https://api.example.com/page2'") + code(")  ") + comment("# Uses same session"))

def display_multithreading():
    print("\n" + "=" * 70)
    print(heading("MULTITHREADING AND MULTIPROCESSING".center(70)))
    print("=" * 70)
    
    print("\n" + heading("Basic Threading:"))
    print(code("import threading"))
    print("\n" + comment("# Define a function to run in a thread"))
    print(code("def worker(num):"))
    print(code("    print(f") + string("'Worker: {num}'") + code(")"))
    print("\n" + comment("# Create and start threads"))
    print(code("threads = []"))
    print(code("for i in range(5):"))
    print(code("    t = threading.Thread(target=worker, args=(i,))"))
    print(code("    threads.append(t)"))
    print(code("    t.start()"))
    print("\n" + comment("# Wait for all threads to complete"))
    print(code("for t in threads:"))
    print(code("    t.join()"))
    
    choice = display_continue_menu()
    if choice == "1":
        print("\n" + heading("Thread Synchronization:"))
        print(comment("# Using locks to prevent race conditions"))
        print(code("import threading"))
        print(code("counter = 0"))
        print(code("counter_lock = threading.Lock()"))
        print("\n" + code("def increment_counter():"))
        print(code("    global counter"))
        print(code("    with counter_lock:  ") + comment("# Acquires and releases the lock"))
        print(code("        current = counter"))
        print(code("        counter = current + 1"))
        print("\n" + comment("# Using events for signaling between threads"))
        print(code("event = threading.Event()"))
        print("\n" + code("def waiter():"))
        print(code("    print(") + string("'Waiter: Waiting for event...'") + code(")"))
        print(code("    event.wait()  ") + comment("# Blocks until the event is set"))
        print(code("    print(") + string("'Waiter: Event is set!'") + code(")"))
        print("\n" + code("def setter():"))
        print(code("    print(") + string("'Setter: Setting the event'") + code(")"))
        print(code("    event.set()  ") + comment("# Set the event, unblocking all waiters"))
        
        choice = display_continue_menu()
        if choice == "1":
            print("\n" + heading("Thread Pools:"))
            print(code("from concurrent.futures import ThreadPoolExecutor"))
            print("\n" + comment("# Define a worker function"))
            print(code("def worker(num):"))
            print(code("    return num * num"))
            print("\n" + comment("# Using a thread pool executor"))
            print(code("with ThreadPoolExecutor(max_workers=4) as executor:"))
            print(code("    ") + comment("# Submit tasks and get futures"))
            print(code("    futures = [executor.submit(worker, i) for i in range(10)]"))
            print(code("    "))
            print(code("    ") + comment("# Get results as they complete"))
            print(code("    for future in futures:"))
            print(code("        result = future.result()  ") + comment("# Waits for the future to complete"))
            print(code("        print(f") + string("'Result: {result}'") + code(")"))
            print("\n" + comment("# Map function with thread pool"))
            print(code("with ThreadPoolExecutor(max_workers=4) as executor:"))
            print(code("    results = list(executor.map(worker, range(10)))"))
            print(code("    print(results)"))
            
            choice = display_continue_menu()
            if choice == "1":
                print("\n" + heading("Multiprocessing:"))
                print(comment("# Multiprocessing uses separate processes instead of threads"))
                print(code("import multiprocessing"))
                print("\n" + code("def process_worker(num):"))
                print(code("    return num * num"))
                print("\n" + comment("# Create and start processes"))
                print(code("if __name__ == '__main__':  ") + comment("# Required for Windows"))
                print(code("    processes = []"))
                print(code("    for i in range(5):"))
                print(code("        p = multiprocessing.Process(target=process_worker, args=(i,))"))
                print(code("        processes.append(p)"))
                print(code("        p.start()"))
                print("\n" + code("    ") + comment("# Wait for processes to complete"))
                print(code("    for p in processes:"))
                print(code("        p.join()"))
                print("\n" + heading("Process Pools:"))
                print(code("from multiprocessing import Pool"))
                print("\n" + code("def process_worker(num):"))
                print(code("    return num * num"))
                print("\n" + code("if __name__ == '__main__':"))
                print(code("    with Pool(processes=4) as pool:"))
                print(code("        results = pool.map(process_worker, range(10))"))
                print(code("        print(results)"))

def display_json():
    print("\n" + "=" * 70)
    print(heading("WORKING WITH JSON".center(70)))
    print("=" * 70)
    
    print("\n" + heading("Basic JSON Operations:"))
    print(code("import json"))
    print("\n" + comment("# Converting Python objects to JSON (serialization)"))
    print(code("data = {"))
    print(code("    ") + string("'name'") + code(": ") + string("'John Doe'") + code(","))
    print(code("    ") + string("'age'") + code(": 30,"))
    print(code("    ") + string("'is_active'") + code(": True,"))
    print(code("    ") + string("'skills'") + code(": [") + string("'Python'") + code(", ") + string("'JavaScript'") + code(", ") + string("'SQL'") + code("],"))
    print(code("    ") + string("'address'") + code(": {") + string("'city'") + code(": ") + string("'New York'") + code(", ") + string("'zip'") + code(": ") + string("'10001'") + code("}"))
    print(code("}"))
    print("\n" + comment("# Convert Python object to JSON string"))
    print(code("json_string = json.dumps(data)"))
    print(code("print(json_string)"))
    
    choice = display_continue_menu()
    if choice == "1":
        print("\n" + heading("Pretty Printing and Formatting:"))
        print(comment("# Convert with pretty formatting"))
        print(code("json_formatted = json.dumps(data, indent=4, sort_keys=True)"))
        print(code("print(json_formatted)"))
        print("\n" + comment("# Writing JSON to a file"))
        print(code("with open(") + string("'data.json'") + code(", ") + string("'w'") + code(") as f:"))
        print(code("    json.dump(data, f, indent=4)"))
        print("\n" + comment("# Converting JSON to Python objects (deserialization)"))
        print(code("json_str = ") + string('\'{"name": "Jane Smith", "age": 28}\''))
        print(code("person = json.loads(json_str)"))
        print(code("print(person[") + string("'name'") + code("])  ") + comment("# Output: Jane Smith"))
        
        choice = display_continue_menu()
        if choice == "1":
            print("\n" + heading("Reading JSON from Files:"))
            print(code("with open(") + string("'data.json'") + code(", ") + string("'r'") + code(") as f:"))
            print(code("    data = json.load(f)"))
            print(code("    print(data[") + string("'name'") + code("])"))
            print("\n" + heading("Handling Complex JSON:"))
            print(comment("# Working with nested JSON structures"))
            print(code("json_data = ") + string('\'{"employees": [{"name": "Alice", "role": "Developer"}, {"name": "Bob", "role": "Manager"}]}\''))
            print(code("data = json.loads(json_data)"))
            print(code("# Access nested elements"))
            print(code("for employee in data[") + string("'employees'") + code("]:"))
            print(code("    print(f") + string("'Name: {employee[\"name\"]}, Role: {employee[\"role\"]}'") + code(")"))
            
            choice = display_continue_menu()
            if choice == "1":
                print("\n" + heading("Custom JSON Encoding and Decoding:"))
                print(code("import json"))
                print(code("from datetime import datetime"))
                print("\n" + comment("# Custom JSON encoder"))
                print(code("class CustomEncoder(json.JSONEncoder):"))
                print(code("    def default(self, obj):"))
                print(code("        if isinstance(obj, datetime):"))
                print(code("            return obj.isoformat()  ") + comment("# Convert datetime to ISO format string"))
                print(code("        return super().default(obj)  ") + comment("# Let the base class handle it"))
                print("\n" + code("data = {") + string("'name'") + code(": ") + string("'John'") + code(", ") + string("'created_at'") + code(": datetime.now()}"))
                print(code("json_str = json.dumps(data, cls=CustomEncoder)"))
                print("\n" + comment("# Custom JSON decoder"))
                print(code("def datetime_decoder(dict_):"))
                print(code("    for key, value in dict_.items():"))
                print(code("        try:"))
                print(code("            dict_[key] = datetime.fromisoformat(value)"))
                print(code("        except (TypeError, ValueError):"))
                print(code("            pass"))
                print(code("    return dict_"))
                print("\n" + code("decoded = json.loads(json_str, object_hook=datetime_decoder)"))

def display_csv():
    print("\n" + "=" * 70)
    print(heading("WORKING WITH CSV FILES".center(70)))
    print("=" * 70)
    
    print("\n" + heading("Reading CSV Files:"))
    print(code("import csv"))
    print("\n" + comment("# Reading a CSV file"))
    print(code("with open(") + string("'data.csv'") + code(", ") + string("'r'") + code(", newline='') as file:"))
    print(code("    reader = csv.reader(file)"))
    print(code("    for row in reader:"))
    print(code("        print(row)  ") + comment("# row is a list of values"))
    print("\n" + comment("# Reading a CSV file with different delimiter"))
    print(code("with open(") + string("'data.tsv'") + code(", ") + string("'r'") + code(", newline='') as file:"))
    print(code("    reader = csv.reader(file, delimiter='\\t')"))
    print(code("    for row in reader:"))
    print(code("        print(row)"))
    
    choice = display_continue_menu()
    if choice == "1":
        print("\n" + heading("Using CSV DictReader:"))
        print(comment("# Reading CSV as dictionaries (using column headers)"))
        print(code("with open(") + string("'data.csv'") + code(", ") + string("'r'") + code(", newline='') as file:"))
        print(code("    reader = csv.DictReader(file)"))
        print(code("    for row in reader:"))
        print(code("        print(row[") + string("'name'") + code("])  ") + comment("# Access by column name"))
        print("\n" + comment("# Specifying fieldnames if CSV doesn't have headers"))
        print(code("with open(") + string("'data.csv'") + code(", ") + string("'r'") + code(", newline='') as file:"))
        print(code("    fieldnames = [") + string("'id'") + code(", ") + string("'name'") + code(", ") + string("'email'") + code("]"))
        print(code("    reader = csv.DictReader(file, fieldnames=fieldnames)"))
        print(code("    for row in reader:"))
        print(code("        print(row)"))
        
        choice = display_continue_menu()
        if choice == "1":
            print("\n" + heading("Writing CSV Files:"))
            print(comment("# Writing a CSV file"))
            print(code("data = ["))
            print(code("    [") + string("'id'") + code(", ") + string("'name'") + code(", ") + string("'email'") + code("],"))
            print(code("    [") + string("'1'") + code(", ") + string("'John Doe'") + code(", ") + string("'john@example.com'") + code("],"))
            print(code("    [") + string("'2'") + code(", ") + string("'Jane Smith'") + code(", ") + string("'jane@example.com'") + code("]"))
            print(code("]"))
            print("\n" + code("with open(") + string("'output.csv'") + code(", ") + string("'w'") + code(", newline='') as file:"))
            print(code("    writer = csv.writer(file)"))
            print(code("    writer.writerows(data)  ") + comment("# Write multiple rows at once"))
            print("\n" + comment("# Writing individual rows"))
            print(code("with open(") + string("'output.csv'") + code(", ") + string("'w'") + code(", newline='') as file:"))
            print(code("    writer = csv.writer(file)"))
            print(code("    writer.writerow([") + string("'id'") + code(", ") + string("'name'") + code(", ") + string("'email'") + code("])  ") + comment("# Header"))
            print(code("    writer.writerow([") + string("'1'") + code(", ") + string("'John Doe'") + code(", ") + string("'john@example.com'") + code("])"))
            
            choice = display_continue_menu()
            if choice == "1":
                print("\n" + heading("Using CSV DictWriter:"))
                print(code("data = ["))
                print(code("    {") + string("'id'") + code(": ") + string("'1'") + code(", ") + string("'name'") + code(": ") + string("'John Doe'") + code(", ") + string("'email'") + code(": ") + string("'john@example.com'") + code("},"))
                print(code("    {") + string("'id'") + code(": ") + string("'2'") + code(", ") + string("'name'") + code(": ") + string("'Jane Smith'") + code(", ") + string("'email'") + code(": ") + string("'jane@example.com'") + code("}"))
                print(code("]"))
                print("\n" + code("with open(") + string("'output.csv'") + code(", ") + string("'w'") + code(", newline='') as file:"))
                print(code("    fieldnames = [") + string("'id'") + code(", ") + string("'name'") + code(", ") + string("'email'") + code("]"))
                print(code("    writer = csv.DictWriter(file, fieldnames=fieldnames)"))
                print(code("    writer.writeheader()  ") + comment("# Write the header row"))
                print(code("    writer.writerows(data)  ") + comment("# Write multiple dictionary rows"))
                print("\n" + heading("Advanced CSV Handling:"))
                print(comment("# Handling different dialects (Excel, etc.)"))
                print(code("with open(") + string("'data.csv'") + code(", ") + string("'r'") + code(", newline='') as file:"))
                print(code("    reader = csv.reader(file, dialect='excel')"))
                print(code("    for row in reader:"))
                print(code("        print(row)"))
                print("\n" + comment("# Handling special characters and quoting"))
                print(code("with open(") + string("'output.csv'") + code(", ") + string("'w'") + code(", newline='') as file:"))
                print(code("    writer = csv.writer(file, quoting=csv.QUOTE_ALL)  ") + comment("# Quote all fields"))
                print(code("    writer.writerow([") + string("'Data with, comma'") + code(", ") + string("'Other \"quoted\" text'") + code("])"))

def display_pdf():
    print("\n" + "=" * 70)
    print(heading("WORKING WITH PDFS".center(70)))
    print("=" * 70)
    
    print("\n" + heading("Reading PDFs with PyPDF2:"))
    print(comment("# Installing PyPDF2"))
    print(code("pip install PyPDF2"))
    print("\n" + comment("# Reading text from a PDF"))
    print(code("import PyPDF2"))
    print("\n" + code("with open(") + string("'document.pdf'") + code(", ") + string("'rb'") + code(") as file:"))
    print(code("    reader = PyPDF2.PdfReader(file)"))
    print(code("    "))
    print(code("    ") + comment("# Get the number of pages"))
    print(code("    num_pages = len(reader.pages)"))
    print(code("    print(f") + string("'Document has {num_pages} pages'") + code(")"))
    print(code("    "))
    print(code("    ") + comment("# Extract text from a specific page"))
    print(code("    page = reader.pages[0]  ") + comment("# First page"))
    print(code("    text = page.extract_text()"))
    print(code("    print(text)"))
    
    choice = display_continue_menu()
    if choice == "1":
        print("\n" + heading("Creating and Modifying PDFs:"))
        print(code("from PyPDF2 import PdfWriter, PdfReader"))
        print("\n" + comment("# Merging multiple PDFs"))
        print(code("merger = PyPDF2.PdfMerger()"))
        print(code("for pdf_file in [") + string("'file1.pdf'") + code(", ") + string("'file2.pdf'") + code(", ") + string("'file3.pdf'") + code("]:"))
        print(code("    merger.append(pdf_file)"))
        print(code("merger.write(") + string("'merged_output.pdf'") + code(")"))
        print(code("merger.close()"))
        print("\n" + comment("# Extracting specific pages"))
        print(code("with open(") + string("'document.pdf'") + code(", ") + string("'rb'") + code(") as file:"))
        print(code("    reader = PdfReader(file)"))
        print(code("    writer = PdfWriter()"))
        print(code("    "))
        print(code("    ") + comment("# Add specific pages to the new PDF"))
        print(code("    writer.add_page(reader.pages[0])  ") + comment("# First page"))
        print(code("    writer.add_page(reader.pages[2])  ") + comment("# Third page"))
        print(code("    "))
        print(code("    ") + comment("# Write to a new PDF"))
        print(code("    with open(") + string("'extracted_pages.pdf'") + code(", ") + string("'wb'") + code(") as output_file:"))
        print(code("        writer.write(output_file)"))
        
        choice = display_continue_menu()
        if choice == "1":
            print("\n" + heading("Advanced PDF Features:"))
            print(comment("# Rotating pages"))
            print(code("with open(") + string("'document.pdf'") + code(", ") + string("'rb'") + code(") as file:"))
            print(code("    reader = PdfReader(file)"))
            print(code("    writer = PdfWriter()"))
            print(code("    "))
            print(code("    ") + comment("# Get the first page and rotate it 90 degrees"))
            print(code("    page = reader.pages[0]"))
            print(code("    page.rotate(90)"))
            print(code("    writer.add_page(page)"))
            print(code("    "))
            print(code("    with open(") + string("'rotated.pdf'") + code(", ") + string("'wb'") + code(") as output_file:"))
            print(code("        writer.write(output_file)"))
            print("\n" + comment("# Working with PDF forms"))
            print(code("reader = PdfReader(") + string("'form.pdf'") + code(")"))
            print(code("writer = PdfWriter()"))
            print(code("writer.append(reader)"))
            print(code("# Update form fields"))
            print(code("writer.update_page_form_field_values("))
            print(code("    writer.pages[0], {") + string("'name'") + code(": ") + string("'John Doe'") + code(", ") + string("'email'") + code(": ") + string("'john@example.com'") + code("}"))
            print(code(")"))
            print(code("# Write the updated form"))
            print(code("with open(") + string("'filled_form.pdf'") + code(", ") + string("'wb'") + code(") as output_file:"))
            print(code("    writer.write(output_file)"))
            
            choice = display_continue_menu()
            if choice == "1":
                print("\n" + heading("PDF Text Extraction with pdfplumber:"))
                print(comment("# Installing pdfplumber (better text extraction)"))
                print(code("pip install pdfplumber"))
                print("\n" + code("import pdfplumber"))
                print(code("with pdfplumber.open(") + string("'document.pdf'") + code(") as pdf:"))
                print(code("    ") + comment("# Extract text from first page"))
                print(code("    first_page = pdf.pages[0]"))
                print(code("    text = first_page.extract_text()"))
                print(code("    print(text)"))
                print("\n" + comment("# Extract tables from a page"))
                print(code("    tables = first_page.extract_tables()"))
                print(code("    for table in tables:"))
                print(code("        for row in table:"))
                print(code("            print(row)"))
                print("\n" + comment("# Extract images (requires pillow)"))
                print(code("    for image in first_page.images:"))
                print(code("        print(f") + string("'Image at: {image[\"x0\"]}, {image[\"y0\"]}, size: {image[\"width\"]}x{image[\"height\"]}'") + code(")"))

def display_web_scraping():
    print("\n" + "=" * 70)
    print(heading("WEB SCRAPING".center(70)))
    print("=" * 70)
    
    print("\n" + heading("Web Scraping with BeautifulSoup:"))
    print(comment("# Installing required libraries"))
    print(code("pip install requests beautifulsoup4"))
    print("\n" + code("import requests"))
    print(code("from bs4 import BeautifulSoup"))
    print("\n" + comment("# Fetch a web page"))
    print(code("url = ") + string("'https://example.com'"))
    print(code("response = requests.get(url)"))
    print(code("html_content = response.text"))
    print("\n" + comment("# Parse the HTML"))
    print(code("soup = BeautifulSoup(html_content, ") + string("'html.parser'") + code(")"))
    print("\n" + comment("# Find elements by tag name"))
    print(code("all_paragraphs = soup.find_all(") + string("'p'") + code(")"))
    print(code("for paragraph in all_paragraphs:"))
    print(code("    print(paragraph.text)"))
    
    choice = display_continue_menu()
    if choice == "1":
        print("\n" + heading("Finding Specific Elements:"))
        print(comment("# Find element by ID"))
        print(code("header = soup.find(id=") + string("'header'") + code(")"))
        print("\n" + comment("# Find elements by class name"))
        print(code("article_items = soup.find_all(") + string("'div'") + code(", class_=") + string("'article'") + code(")"))
        print("\n" + comment("# Find elements using CSS selectors"))
        print(code("results = soup.select(") + string("'#main-content .item h2'") + code(")"))
        print("\n" + comment("# Find elements by attribute"))
        print(code("links = soup.find_all(") + string("'a'") + code(", href=True)"))
        print(code("for link in links:"))
        print(code("    print(f") + string("'Link URL: {link[\"href\"]}, Text: {link.text}'") + code(")"))
        
        choice = display_continue_menu()
        if choice == "1":
            print("\n" + heading("Navigating the HTML Structure:"))
            print(comment("# Navigating down (children)"))
            print(code("main_div = soup.find(") + string("'div'") + code(", class_=") + string("'main'") + code(")"))
            print(code("child_paragraphs = main_div.find_all(") + string("'p'") + code(", recursive=False)  ") + comment("# Direct children only"))
            print("\n" + comment("# Navigating up (parents)"))
            print(code("element = soup.find(") + string("'span'") + code(", class_=") + string("'highlight'") + code(")"))
            print(code("parent = element.parent"))
            print("\n" + comment("# Navigating sideways (siblings)"))
            print(code("first_li = soup.find(") + string("'li'") + code(")"))
            print(code("next_li = first_li.find_next_sibling(") + string("'li'") + code(")"))
            print(code("prev_li = first_li.find_previous_sibling(") + string("'li'") + code(")"))
            
            choice = display_continue_menu()
            if choice == "1":
                print("\n" + heading("Scraping Data from Tables:"))
                print(code("table = soup.find(") + string("'table'") + code(")"))
                print(code("rows = table.find_all(") + string("'tr'") + code(")"))
                print(code("for row in rows:"))
                print(code("    cells = row.find_all([") + string("'td'") + code(", ") + string("'th'") + code("])"))
                print(code("    row_data = [cell.text.strip() for cell in cells]"))
                print(code("    print(row_data)"))
                print("\n" + heading("Web Scraping with Selenium:"))
                print(comment("# For dynamic content that requires JavaScript"))
                print(code("pip install selenium webdriver-manager"))
                print("\n" + code("from selenium import webdriver"))
                print(code("from selenium.webdriver.chrome.service import Service"))
                print(code("from webdriver_manager.chrome import ChromeDriverManager"))
                print(code("from selenium.webdriver.common.by import By"))
                print("\n" + comment("# Setup the driver"))
                print(code("service = Service(ChromeDriverManager().install())"))
                print(code("driver = webdriver.Chrome(service=service)"))
                print("\n" + comment("# Navigate to a website"))
                print(code("driver.get(") + string("'https://example.com'") + code(")"))
                print(code("driver.implicitly_wait(10)  ") + comment("# Wait for page to load"))
                
                choice = display_continue_menu()
                if choice == "1":
                    print("\n" + comment("# Find elements"))
                    print(code("elements = driver.find_elements(By.CSS_SELECTOR, ") + string("'.product-item'") + code(")"))
                    print(code("for element in elements:"))
                    print(code("    name = element.find_element(By.CLASS_NAME, ") + string("'name'") + code(").text"))
                    print(code("    price = element.find_element(By.CLASS_NAME, ") + string("'price'") + code(").text"))
                    print(code("    print(f") + string("'Product: {name}, Price: {price}'") + code(")"))
                    print("\n" + comment("# Interacting with the page"))
                    print(code("search_box = driver.find_element(By.ID, ") + string("'search'") + code(")"))
                    print(code("search_box.send_keys(") + string("'Python books'") + code(")"))
                    print(code("search_box.submit()"))
                    print("\n" + comment("# Wait for specific elements to appear"))
                    print(code("from selenium.webdriver.support.ui import WebDriverWait"))
                    print(code("from selenium.webdriver.support import expected_conditions as EC"))
                    print(code("element = WebDriverWait(driver, 10).until("))
                    print(code("    EC.presence_of_element_located((By.ID, ") + string("'results'") + code("))"))
                    print(code(")"))
                    print("\n" + comment("# Close the browser when done"))
                    print(code("driver.quit()"))

def display_pandas():
    print("\n" + "=" * 70)
    print(heading("DATA ANALYSIS WITH PANDAS".center(70)))
    print("=" * 70)
    
    print("\n" + heading("Basic Pandas Operations:"))
    print(comment("# Installing pandas"))
    print(code("pip install pandas"))
    print("\n" + code("import pandas as pd"))
    print(code("import numpy as np"))
    print("\n" + comment("# Creating a DataFrame"))
    print(code("# From a dictionary"))
    print(code("data = {"))
    print(code("    ") + string("'Name'") + code(": [") + string("'John'") + code(", ") + string("'Anna'") + code(", ") + string("'Peter'") + code(", ") + string("'Linda'") + code("],"))
    print(code("    ") + string("'Age'") + code(": [28, 34, 29, 42],"))
    print(code("    ") + string("'City'") + code(": [") + string("'New York'") + code(", ") + string("'Boston'") + code(", ") + string("'San Francisco'") + code(", ") + string("'Chicago'") + code("]"))
    print(code("}"))
    print(code("df = pd.DataFrame(data)"))
    print(code("print(df)"))
    
    choice = display_continue_menu()
    if choice == "1":
        print("\n" + heading("Reading and Writing Data:"))
        print(comment("# Reading data from CSV"))
        print(code("df = pd.read_csv(") + string("'data.csv'") + code(")"))
        print("\n" + comment("# Reading data from Excel"))
        print(code("df = pd.read_excel(") + string("'data.xlsx'") + code(", sheet_name=") + string("'Sheet1'") + code(")"))
        print("\n" + comment("# Reading data from JSON"))
        print(code("df = pd.read_json(") + string("'data.json'") + code(")"))
        print("\n" + comment("# Reading data from a database"))
        print(code("import sqlite3"))
        print(code("conn = sqlite3.connect(") + string("'database.db'") + code(")"))
        print(code("df = pd.read_sql(") + string("'SELECT * FROM users'") + code(", conn)"))
        print("\n" + comment("# Writing data"))
        print(code("df.to_csv(") + string("'output.csv'") + code(", index=False)"))
        print(code("df.to_excel(") + string("'output.xlsx'") + code(", index=False)"))
        print(code("df.to_json(") + string("'output.json'") + code(", orient=") + string("'records'") + code(")"))
        
        choice = display_continue_menu()
        if choice == "1":
            print("\n" + heading("Data Exploration and Manipulation:"))
            print(comment("# Basic information about DataFrame"))
            print(code("df.info()        ") + comment("# Summary of DataFrame"))
            print(code("df.describe()    ") + comment("# Statistical summary of numeric columns"))
            print(code("df.shape         ") + comment("# (rows, columns)"))
            print(code("df.columns       ") + comment("# Column names"))
            print(code("df.dtypes        ") + comment("# Data types of columns"))
            print(code("df.head(10)      ") + comment("# First 10 rows"))
            print(code("df.tail(5)       ") + comment("# Last 5 rows"))
            print("\n" + comment("# Selecting data"))
            print(code("# Select a column"))
            print(code("df[") + string("'Name'") + code("]"))
            print(code("# Select multiple columns"))
            print(code("df[[") + string("'Name'") + code(", ") + string("'Age'") + code("]]"))
            print(code("# Select rows by index"))
            print(code("df.loc[0]        ") + comment("# First row"))
            print(code("df.loc[1:3]      ") + comment("# Rows 1 to 3"))
            print(code("# Select rows by condition"))
            print(code("df[df[") + string("'Age'") + code("] > 30]"))
            
            choice = display_continue_menu()
            if choice == "1":
                print("\n" + heading("Data Cleaning and Transformation:"))
                print(comment("# Handling missing values"))
                print(code("df.isna().sum()    ") + comment("# Count of missing values per column"))
                print(code("df.dropna()        ") + comment("# Drop rows with any missing values"))
                print(code("df.fillna(value=0) ") + comment("# Fill missing values with 0"))
                print("\n" + comment("# Removing duplicates"))
                print(code("df.drop_duplicates(subset=[") + string("'Name'") + code("], keep=") + string("'first'") + code(")"))
                print("\n" + comment("# Renaming columns"))
                print(code("df.rename(columns={") + string("'Name'") + code(": ") + string("'FullName'") + code(", ") + string("'City'") + code(": ") + string("'Location'") + code("})"))
                print("\n" + comment("# Creating new columns"))
                print(code("df[") + string("'IsAdult'") + code("] = df[") + string("'Age'") + code("] >= 18"))
                print(code("df[") + string("'NameLength'") + code("] = df[") + string("'Name'") + code("].str.len()"))
                
                choice = display_continue_menu()
                if choice == "1":
                    print("\n" + heading("Data Analysis and Aggregation:"))
                    print(comment("# Grouping and aggregation"))
                    print(code("# Group by City and get mean age"))
                    print(code("df.groupby(") + string("'City'") + code(")[") + string("'Age'") + code("].mean()"))
                    print("\n" + comment("# Multiple aggregations"))
                    print(code("df.groupby(") + string("'City'") + code(").agg({"))
                    print(code("    ") + string("'Age'") + code(": [") + string("'min'") + code(", ") + string("'max'") + code(", ") + string("'mean'") + code("],"))
                    print(code("    ") + string("'Name'") + code(": ") + string("'count'"))
                    print(code("})"))
                    print("\n" + comment("# Pivot tables"))
                    print(code("pivot_table = df.pivot_table("))
                    print(code("    values=") + string("'Age'") + code(","))
                    print(code("    index=") + string("'City'") + code(","))
                    print(code("    columns=") + string("'IsAdult'") + code(","))
                    print(code("    aggfunc=") + string("'mean'"))
                    print(code(")"))
                    print("\n" + comment("# Time series analysis"))
                    print(code("# Create a date range"))
                    print(code("dates = pd.date_range(") + string("'2023-01-01'") + code(", periods=10, freq=") + string("'D'") + code(")"))
                    print(code("ts = pd.Series(np.random.randn(10), index=dates)"))
                    print(code("# Resample to weekly frequency"))
                    print(code("ts.resample(") + string("'W'") + code(").mean()"))

def display_advanced_python():
    print("\n" + "=" * 70)
    print(heading("ADVANCED PYTHON CONCEPTS".center(70)))
    print("=" * 70)
    
    print("\n" + heading("Context Managers:"))
    print(comment("# Creating a custom context manager"))
    print(code("class FileManager:"))
    print(code("    def __init__(self, filename, mode):"))
    print(code("        self.filename = filename"))
    print(code("        self.mode = mode"))
    print(code("        self.file = None"))
    print(code("        "))
    print(code("    def __enter__(self):"))
    print(code("        self.file = open(self.filename, self.mode)"))
    print(code("        return self.file"))
    print(code("        "))
    print(code("    def __exit__(self, exc_type, exc_val, exc_tb):"))
    print(code("        if self.file:"))
    print(code("            self.file.close()"))
    print(code("        ") + comment("# Return True to suppress exceptions, False to propagate them"))
    print(code("        return False"))
    print("\n" + comment("# Using the context manager"))
    print(code("with FileManager(") + string("'data.txt'") + code(", ") + string("'r'") + code(") as file:"))
    print(code("    content = file.read()"))
    print("\n" + comment("# Context manager using the contextlib module"))
    print(code("from contextlib import contextmanager"))
    print("\n" + code("@contextmanager"))
    print(code("def file_manager(filename, mode):"))
    print(code("    try:"))
    print(code("        file = open(filename, mode)"))
    print(code("        yield file"))
    print(code("    finally:"))
    print(code("        file.close()"))
    
    choice = display_continue_menu()
    if choice == "1":
        print("\n" + heading("Generators and Coroutines:"))
        print(comment("# Simple generator function"))
        print(code("def count_up_to(max):"))
        print(code("    count = 1"))
        print(code("    while count <= max:"))
        print(code("        yield count"))
        print(code("        count += 1"))
        print("\n" + comment("# Using the generator"))
        print(code("for number in count_up_to(5):"))
        print(code("    print(number)  ") + comment("# Prints 1, 2, 3, 4, 5"))
        print("\n" + comment("# Generator expressions"))
        print(code("squares = (x**2 for x in range(10))"))
        print(code("next(squares)  ") + comment("# 0"))
        print(code("next(squares)  ") + comment("# 1"))
        print("\n" + comment("# Coroutines (generator with both yield and send)"))
        print(code("def receiver():"))
        print(code("    print(") + string("'Ready to receive!'") + code(")"))
        print(code("    while True:"))
        print(code("        value = yield"))
        print(code("        print(f") + string("'Got: {value}'") + code(")"))
        print("\n" + code("coro = receiver()"))
        print(code("next(coro)  ") + comment("# Advance to the first yield"))
        print(code("coro.send(") + string("'Hello'") + code(")  ") + comment("# Send value to the coroutine"))
        
        choice = display_continue_menu()
        if choice == "1":
            print("\n" + heading("Metaclasses:"))
            print(comment("# Basic metaclass example"))
            print(code("class Meta(type):"))
            print(code("    def __new__(mcs, name, bases, attrs):"))
            print(code("        ") + comment("# Add a new method to the class"))
            print(code("        attrs[") + string("'added_by_meta'") + code("] = lambda self: ") + string("'This method was added by the metaclass'"))
            print(code("        ") + comment("# Print out class creation info"))
            print(code("        print(f") + string("'Creating class {name}'") + code(")"))
            print(code("        return super().__new__(mcs, name, bases, attrs)"))
            print("\n" + code("class MyClass(metaclass=Meta):"))
            print(code("    def __init__(self, value):"))
            print(code("        self.value = value"))
            print("\n" + code("obj = MyClass(42)"))
            print(code("print(obj.added_by_meta())  ") + comment("# Calls the method added by the metaclass"))
            print("\n" + heading("Descriptors:"))
            print(comment("# Building a descriptor for validation"))
            print(code("class Positive:"))
            print(code("    def __init__(self):"))
            print(code("        self.name = None"))
            print(code("    "))
            print(code("    def __set_name__(self, owner, name):"))
            print(code("        self.name = name"))
            print(code("    "))
            print(code("    def __get__(self, instance, owner):"))
            print(code("        if instance is None:"))
            print(code("            return self"))
            print(code("        return instance.__dict__[self.name]"))
            print(code("    "))
            print(code("    def __set__(self, instance, value):"))
            print(code("        if value <= 0:"))
            print(code("            raise ValueError(") + string("'Value must be positive'") + code(")"))
            print(code("        instance.__dict__[self.name] = value"))
            
            choice = display_continue_menu()
            if choice == "1":
                print("\n" + comment("# Using the descriptor"))
                print(code("class Product:"))
                print(code("    price = Positive()"))
                print(code("    quantity = Positive()"))
                print(code("    "))
                print(code("    def __init__(self, price, quantity):"))
                print(code("        self.price = price"))
                print(code("        self.quantity = quantity"))
                print(code("    "))
                print(code("    def total(self):"))
                print(code("        return self.price * self.quantity"))
                print("\n" + code("product = Product(10, 5)"))
                print(code("print(product.total())  ") + comment("# 50"))
                print(code("# product.price = -10  ") + comment("# Raises ValueError"))
                print("\n" + heading("Abstract Base Classes:"))
                print(code("from abc import ABC, abstractmethod"))
                print("\n" + code("class Vehicle(ABC):"))
                print(code("    @abstractmethod"))
                print(code("    def start(self):"))
                print(code("        pass"))
                print(code("    "))
                print(code("    @abstractmethod"))
                print(code("    def stop(self):"))
                print(code("        pass"))
                print(code("    "))
                print(code("    def honk(self):"))
                print(code("        return ") + string("'Honk! Honk!'") + code(""))
                print("\n" + code("class Car(Vehicle):"))
                print(code("    def start(self):"))
                print(code("        return ") + string("'Car started'") + code(""))
                print(code("    "))
                print(code("    def stop(self):"))
                print(code("        return ") + string("'Car stopped'") + code(""))
                print("\n" + code("# vehicle = Vehicle()  ") + comment("# Can't instantiate abstract class"))
                print(code("car = Car()"))
                print(code("print(car.start())"))
                print(code("print(car.honk())"))

def main():
    while True:
        display_header()
        display_main_menu()
        choice = input("\nEnter your choice: ")
        
        if choice == "0":
            print(f"\n{Fore.GREEN}Thank you for using the Advanced Python Cheat Sheet. Goodbye!{Style.RESET_ALL}")
            break
        elif choice == "1":
            display_api_calls()
        elif choice == "2":
            display_multithreading()
        elif choice == "3":
            display_json()
        elif choice == "4":
            display_csv()
        elif choice == "5":
            display_pdf()
        elif choice == "6":
            display_web_scraping()
        elif choice == "7":
            display_pandas()
        elif choice == "8":
            display_advanced_python()
        elif choice == "9":
            display_help()
        else:
            print(f"\n{Fore.RED}Invalid choice. Please try again.{Style.RESET_ALL}")

if __name__ == "__main__":
    main()
