def display_header():
    print("\n" + "=" * 60)
    print("INTERMEDIATE PYTHON CHEAT SHEET".center(60))
    print("=" * 60)

def display_main_menu():
    print("\nPlease select from the following options:\n")
    print("[1] File Handling")
    print("[2] Exception Handling")
    print("[3] Regular Expressions")
    print("[4] Decorators")
    print("[5] Virtual Environments")
    print("[6] Pip Package Management")
    print("[7] Datetime Module")
    print("[8] Object-Oriented Programming")
    print("[9] Help")
    print("[0] Exit")

def display_continue_menu():
    print("\n[1] Continue")
    print("[0] Main Menu")
    choice = input("\nEnter your choice: ")
    return choice

def display_help():
    print("\n" + "=" * 60)
    print("HELP".center(60))
    print("=" * 60)
    print("\nThis is an intermediate Python cheat sheet program.")
    print("Select a topic number to view information about that topic.")
    print("After viewing a topic, you can continue for more information")
    print("or return to the main menu.")
    print("Select '0' to exit the program.")

def display_file_handling():
    print("\n" + "=" * 60)
    print("FILE HANDLING".center(60))
    print("=" * 60)
    
    print("\nOpening and Closing Files:")
    print("# Basic file opening (always close manually)")
    print("file = open('filename.txt', 'r')  # 'r' for read mode")
    print("content = file.read()")
    print("file.close()")
    print("\n# Using context manager (recommended)")
    print("with open('filename.txt', 'r') as file:")
    print("    content = file.read()  # File automatically closes after block")
    
    choice = display_continue_menu()
    if choice == "1":
        print("\nFile Opening Modes:")
        print("'r'  - Read (default)")
        print("'w'  - Write (creates new file or truncates existing)")
        print("'a'  - Append (creates new file or appends to existing)")
        print("'r+' - Read and write")
        print("'b'  - Binary mode (add to other modes like 'rb' or 'wb')")
        print("'t'  - Text mode (default)")
        print("\nReading Files:")
        print("with open('file.txt', 'r') as f:")
        print("    content = f.read()           # Read entire file as string")
        print("    lines = f.readlines()        # Read all lines into a list")
        print("    first_line = f.readline()    # Read single line")
        print("    # Iterate through lines")
        print("    for line in f:")
        print("        print(line.strip())")
        
        choice = display_continue_menu()
        if choice == "1":
            print("\nWriting Files:")
            print("with open('file.txt', 'w') as f:")
            print("    f.write('Hello, World!')         # Write string")
            print("    f.writelines(['Line1\\n', 'Line2\\n'])  # Write list of strings")
            print("\n# Appending to a file")
            print("with open('file.txt', 'a') as f:")
            print("    f.write('\\nAppended text')")
            print("\nFile System Operations (os module):")
            print("import os")
            print("os.mkdir('dirname')            # Create directory")
            print("os.makedirs('dir1/dir2')       # Create nested directories")
            print("os.remove('filename.txt')      # Delete file")
            print("os.rmdir('dirname')            # Delete empty directory")
            print("os.path.exists('path')         # Check if path exists")
            print("os.path.isfile('path')         # Check if path is a file")
            print("os.path.isdir('path')          # Check if path is a directory")
            print("os.listdir('dirname')          # List contents of directory")

def display_exception_handling():
    print("\n" + "=" * 60)
    print("EXCEPTION HANDLING".center(60))
    print("=" * 60)
    
    print("\nBasic Try-Except Structure:")
    print("try:")
    print("    # Code that might raise an exception")
    print("    result = 10 / 0")
    print("except ZeroDivisionError:")
    print("    # Code to handle the specific exception")
    print("    print('Cannot divide by zero!')")
    
    choice = display_continue_menu()
    if choice == "1":
        print("\nHandling Multiple Exceptions:")
        print("try:")
        print("    num = int(input('Enter a number: '))")
        print("    result = 10 / num")
        print("except ZeroDivisionError:")
        print("    print('Cannot divide by zero!')")
        print("except ValueError:")
        print("    print('Please enter a valid number!')")
        print("except Exception as e:")
        print("    print(f'An error occurred: {e}')")
        print("\nTry-Except-Else-Finally:")
        print("try:")
        print("    file = open('data.txt', 'r')")
        print("except FileNotFoundError:")
        print("    print('File not found!')")
        print("else:")
        print("    # Code that runs if no exception was raised")
        print("    print('File opened successfully')")
        print("    content = file.read()")
        print("finally:")
        print("    # Code that always runs, regardless of exception")
        print("    file.close()")
        
        choice = display_continue_menu()
        if choice == "1":
            print("\nRaising Exceptions:")
            print("def divide(a, b):")
            print("    if b == 0:")
            print("        raise ValueError('Cannot divide by zero')")
            print("    return a / b")
            print("\nDefining Custom Exceptions:")
            print("class CustomError(Exception):")
            print("    def __init__(self, message):")
            print("        self.message = message")
            print("        super().__init__(self.message)")
            print("\n# Using custom exception")
            print("def process_age(age):")
            print("    if age < 0:")
            print("        raise CustomError('Age cannot be negative')")
            print("\nAssertions:")
            print("def calculate_square_root(num):")
            print("    assert num >= 0, 'Input must be non-negative'")
            print("    return num ** 0.5")

def display_regex():
    print("\n" + "=" * 60)
    print("REGULAR EXPRESSIONS".center(60))
    print("=" * 60)
    
    print("\nBasic Regex with the re Module:")
    print("import re")
    print("\n# Simple pattern matching")
    print("pattern = r'python'")
    print("text = 'I love python programming'")
    print("result = re.search(pattern, text)  # Returns match object or None")
    print("if result:")
    print("    print('Pattern found!')")
    
    choice = display_continue_menu()
    if choice == "1":
        print("\nCommon Methods:")
        print("re.search(pattern, string)    # Returns first match")
        print("re.match(pattern, string)     # Matches at the beginning only")
        print("re.findall(pattern, string)   # Returns all matches as list of strings")
        print("re.finditer(pattern, string)  # Returns an iterator of match objects")
        print("re.sub(pattern, repl, string) # Replaces matches with repl")
        print("re.split(pattern, string)     # Splits string at matches")
        print("\nMetacharacters:")
        print(". - Any character except newline")
        print("^ - Start of string")
        print("$ - End of string")
        print("* - 0 or more repetitions")
        print("+ - 1 or more repetitions")
        print("? - 0 or 1 repetition")
        print("{n} - Exactly n repetitions")
        print("{n,} - n or more repetitions")
        print("{n,m} - Between n and m repetitions")
        
        choice = display_continue_menu()
        if choice == "1":
            print("\nCharacter Classes:")
            print("[abc] - Any character a, b, or c")
            print("[^abc] - Any character except a, b, or c")
            print("[a-z] - Any character from a to z")
            print("[0-9] - Any digit")
            print("\\w - Word character (alphanumeric + underscore)")
            print("\\W - Non-word character")
            print("\\d - Digit")
            print("\\D - Non-digit")
            print("\\s - Whitespace")
            print("\\S - Non-whitespace")
            print("\nGroups and Capturing:")
            print("(pattern) - Capturing group")
            print("(?:pattern) - Non-capturing group")
            print("a|b - a or b")
            print("\n# Example with groups")
            print("pattern = r'(\\d{3})-(\\d{3})-(\\d{4})'")
            print("text = 'Call 555-123-4567 for assistance'")
            print("match = re.search(pattern, text)")
            print("if match:")
            print("    area_code = match.group(1)  # '555'")
            print("    print(f'Area code: {area_code}')")

def display_decorators():
    print("\n" + "=" * 60)
    print("DECORATORS".center(60))
    print("=" * 60)
    
    print("\nBasic Decorator:")
    print("def my_decorator(func):")
    print("    def wrapper():")
    print("        print('Something before the function call')")
    print("        func()")
    print("        print('Something after the function call')")
    print("    return wrapper")
    print("\n# Using the decorator")
    print("@my_decorator")
    print("def say_hello():")
    print("    print('Hello!')")
    print("\n# Equivalent to: say_hello = my_decorator(say_hello)")
    print("# Calling the decorated function")
    print("say_hello()")
    
    choice = display_continue_menu()
    if choice == "1":
        print("\nDecorators with Arguments:")
        print("def my_decorator(func):")
        print("    def wrapper(*args, **kwargs):")
        print("        print('Before function call')")
        print("        result = func(*args, **kwargs)")
        print("        print('After function call')")
        print("        return result")
        print("    return wrapper")
        print("\n@my_decorator")
        print("def add(a, b):")
        print("    return a + b")
        print("\n# Now add can take arguments")
        print("result = add(3, 5)  # Returns 8")
        print("\nDecorators with Parameters:")
        print("def repeat(n):")
        print("    def decorator(func):")
        print("        def wrapper(*args, **kwargs):")
        print("            results = []")
        print("            for _ in range(n):")
        print("                results.append(func(*args, **kwargs))")
        print("            return results")
        print("        return wrapper")
        print("    return decorator")
        
        choice = display_continue_menu()
        if choice == "1":
            print("\n# Using parameterized decorator")
            print("@repeat(3)")
            print("def greet(name):")
            print("    return f'Hello, {name}!'")
            print("\n# Calls greet('Alice') three times and returns the results as a list")
            print("results = greet('Alice')  # ['Hello, Alice!', 'Hello, Alice!', 'Hello, Alice!']")
            print("\nPractical Decorator Examples:")
            print("# Timing decorator")
            print("import time")
            print("def timing_decorator(func):")
            print("    def wrapper(*args, **kwargs):")
            print("        start_time = time.time()")
            print("        result = func(*args, **kwargs)")
            print("        end_time = time.time()")
            print("        print(f'Function {func.__name__} took {end_time - start_time:.4f} seconds')")
            print("        return result")
            print("    return wrapper")
            print("\n# Memoization decorator (caching)")
            print("def memoize(func):")
            print("    cache = {}")
            print("    def wrapper(*args):")
            print("        if args not in cache:")
            print("            cache[args] = func(*args)")
            print("        return cache[args]")
            print("    return wrapper")

def display_virtual_environments():
    print("\n" + "=" * 60)
    print("VIRTUAL ENVIRONMENTS".center(60))
    print("=" * 60)
    
    print("\nVirtual Environment Basics:")
    print("- Virtual environments are isolated Python environments")
    print("- They allow projects to have their own dependencies")
    print("- Helps avoid version conflicts between different projects")
    print("- Each virtual environment has its own Python binary and packages")
    
    choice = display_continue_menu()
    if choice == "1":
        print("\nCreating Virtual Environments:")
        print("# Using venv (built-in since Python 3.3)")
        print("python -m venv myenv")
        print("\n# Using virtualenv (third-party)")
        print("pip install virtualenv")
        print("virtualenv myenv")
        print("\nActivating Virtual Environments:")
        print("# Windows")
        print("myenv\\Scripts\\activate")
        print("\n# macOS/Linux")
        print("source myenv/bin/activate")
        print("\n# You'll see the environment name in your prompt when active")
        print("(myenv) $")
        
        choice = display_continue_menu()
        if choice == "1":
            print("\nDeactivating Virtual Environments:")
            print("deactivate")
            print("\nInstalling Packages in Virtual Environment:")
            print("pip install package_name")
            print("\nSaving/Sharing Environment Dependencies:")
            print("# Generate requirements.txt")
            print("pip freeze > requirements.txt")
            print("\n# Install from requirements.txt")
            print("pip install -r requirements.txt")
            print("\nVirtual Environment Best Practices:")
            print("- Create one virtual environment per project")
            print("- Add virtual environment directories to .gitignore")
            print("- Use requirements.txt to track dependencies")
            print("- Use descriptive names for your environments")

def display_pip_management():
    print("\n" + "=" * 60)
    print("PIP PACKAGE MANAGEMENT".center(60))
    print("=" * 60)
    
    print("\nBasic Pip Commands:")
    print("pip --version                   # Check pip version")
    print("pip install package_name        # Install a package")
    print("pip install package_name==1.2.3 # Install specific version")
    print("pip install -U package_name     # Upgrade a package")
    print("pip uninstall package_name      # Uninstall a package")
    print("pip list                        # List installed packages")
    
    choice = display_continue_menu()
    if choice == "1":
        print("\nRequirements Files:")
        print("pip freeze > requirements.txt    # Save current packages to file")
        print("pip install -r requirements.txt  # Install from requirements file")
        print("\nSearching for Packages:")
        print("pip search search_term  # Search PyPI for packages")
        print("\nInstalling from Different Sources:")
        print("pip install git+https://github.com/user/repo.git  # Install from Git")
        print("pip install -e .                            # Install local package in development mode")
        print("pip install package_name --user             # Install to user directory instead of system")
        
        choice = display_continue_menu()
        if choice == "1":
            print("\nPip Configuration:")
            print("pip config list                         # Show current configuration")
            print("pip config set global.index-url URL     # Set custom package index")
            print("pip config set global.trusted-host hostname  # Set trusted host")
            print("\nAdvanced Features:")
            print("pip download package_name -d /path/to/dir  # Download without installing")
            print("pip wheel package_name -w /path/to/dir     # Build wheel package")
            print("pip install --no-deps package_name         # Install without dependencies")
            print("pip show package_name                      # Show package details")
            print("pip check                                  # Verify installed packages have compatible dependencies")

def display_datetime():
    print("\n" + "=" * 60)
    print("DATETIME MODULE".center(60))
    print("=" * 60)
    
    print("\nBasic Datetime Usage:")
    print("from datetime import datetime, date, time, timedelta")
    print("\n# Get current date and time")
    print("now = datetime.now()")
    print("today = date.today()")
    print("\n# Creating datetime objects")
    print("dt = datetime(2023, 1, 15, 10, 30, 45)  # Year, month, day, hour, minute, second")
    print("d = date(2023, 1, 15)")
    print("t = time(10, 30, 45)")
    
    choice = display_continue_menu()
    if choice == "1":
        print("\nFormatting Dates and Times:")
        print("# Using strftime() to format as string")
        print("now.strftime('%Y-%m-%d')            # '2023-01-15'")
        print("now.strftime('%H:%M:%S')            # '10:30:45'")
        print("now.strftime('%Y-%m-%d %H:%M:%S')   # '2023-01-15 10:30:45'")
        print("now.strftime('%A, %B %d, %Y')       # 'Sunday, January 15, 2023'")
        print("\n# Parsing strings into datetime objects")
        print("datetime.strptime('2023-01-15', '%Y-%m-%d')")
        print("datetime.strptime('10:30:45', '%H:%M:%S')")
        print("datetime.strptime('2023-01-15 10:30:45', '%Y-%m-%d %H:%M:%S')")
        
        choice = display_continue_menu()
        if choice == "1":
            print("\nDatetime Arithmetic:")
            print("# Using timedelta for date arithmetic")
            print("delta = timedelta(days=7, hours=3, minutes=15)  # Create a time difference")
            print("future_date = now + delta                       # Add time")
            print("past_date = now - delta                         # Subtract time")
            print("difference = future_date - past_date            # Get difference as timedelta")
            print("days_difference = difference.days               # Get days component")
            print("seconds_difference = difference.seconds         # Get seconds component")
            print("total_seconds = difference.total_seconds()      # Get total seconds")
            print("\n# Date properties and methods")
            print("now.year                   # Year as integer")
            print("now.month                  # Month as integer")
            print("now.day                    # Day as integer")
            print("now.hour                   # Hour as integer")
            print("now.minute                 # Minute as integer")
            print("now.second                 # Second as integer")
            print("now.weekday()              # Day of week as integer (0=Monday, 6=Sunday)")
            print("now.isoweekday()           # Day of week as integer (1=Monday, 7=Sunday)")

def display_oop():
    print("\n" + "=" * 60)
    print("OBJECT-ORIENTED PROGRAMMING".center(60))
    print("=" * 60)
    
    print("\nClass Definition:")
    print("class Person:")
    print("    # Class variable (shared by all instances)")
    print("    species = 'Human'")
    print("    ")
    print("    # Constructor method")
    print("    def __init__(self, name, age):")
    print("        # Instance variables (unique to each instance)")
    print("        self.name = name")
    print("        self.age = age")
    print("    ")
    print("    # Instance method")
    print("    def greet(self):")
    print("        return f'Hello, my name is {self.name}'")
    print("    ")
    print("    # String representation")
    print("    def __str__(self):")
    print("        return f'Person: {self.name}, {self.age} years old'")
    
    choice = display_continue_menu()
    if choice == "1":
        print("\nCreating and Using Objects:")
        print("# Create instances of the class")
        print("person1 = Person('Alice', 30)")
        print("person2 = Person('Bob', 25)")
        print("\n# Accessing attributes and methods")
        print("person1.name                # 'Alice'")
        print("person1.age                 # 30")
        print("person1.species             # 'Human'")
        print("person1.greet()             # 'Hello, my name is Alice'")
        print("print(person1)              # 'Person: Alice, 30 years old'")
        print("\n# Modifying attributes")
        print("person1.age = 31            # Change instance attribute")
        print("Person.species = 'Homosapien'  # Change class attribute for all instances")
        
        choice = display_continue_menu()
        if choice == "1":
            print("\nInheritance:")
            print("class Student(Person):")
            print("    # Child class inherits from Person")
            print("    def __init__(self, name, age, student_id):")
            print("        # Call parent constructor")
            print("        super().__init__(name, age)")
            print("        self.student_id = student_id")
            print("    ")
            print("    # Override parent method")
            print("    def greet(self):")
            print("        return f'{super().greet()} and I am a student'")
            print("    ")
            print("    # New method in child class")
            print("    def study(self, subject):")
            print("        return f'{self.name} is studying {subject}'")
            
            choice = display_continue_menu()
            if choice == "1":
                print("\nEncapsulation and Access Modifiers:")
                print("class BankAccount:")
                print("    def __init__(self, owner, balance=0):")
                print("        self.owner = owner         # Public attribute")
                print("        self._balance = balance    # Protected attribute (convention)")
                print("        self.__account_num = '12345'  # Private attribute")
                print("    ")
                print("    def deposit(self, amount):")
                print("        if amount > 0:")
                print("            self._balance += amount")
                print("            return True")
                print("        return False")
                print("    ")
                print("    def withdraw(self, amount):")
                print("        if 0 < amount <= self._balance:")
                print("            self._balance -= amount")
                print("            return True")
                print("        return False")
                print("    ")
                print("    def get_balance(self):")
                print("        return self._balance")
                
                choice = display_continue_menu()
                if choice == "1":
                    print("\nPolymorphism:")
                    print("class Animal:")
                    print("    def speak(self):")
                    print("        pass")
                    print("\nclass Dog(Animal):")
                    print("    def speak(self):")
                    print("        return 'Woof!'")
                    print("\nclass Cat(Animal):")
                    print("    def speak(self):")
                    print("        return 'Meow!'")
                    print("\n# Polymorphic function")
                    print("def animal_sound(animal):")
                    print("    return animal.speak()")
                    print("\n# Call with different objects")
                    print("dog = Dog()")
                    print("cat = Cat()")
                    print("animal_sound(dog)  # 'Woof!'")
                    print("animal_sound(cat)  # 'Meow!'")
                    print("\nClass and Static Methods:")
                    print("class MathUtils:")
                    print("    # Class variable")
                    print("    pi = 3.14159")
                    print("    ")
                    print("    # Instance method (needs self)")
                    print("    def add(self, a, b):")
                    print("        return a + b")
                    print("    ")
                    print("    # Class method (needs cls)")
                    print("    @classmethod")
                    print("    def circle_area(cls, radius):")
                    print("        return cls.pi * radius * radius")
                    print("    ")
                    print("    # Static method (needs neither self nor cls)")
                    print("    @staticmethod")
                    print("    def square_area(side):")
                    print("        return side * side")

def main():
    while True:
        display_header()
        display_main_menu()
        choice = input("\nEnter your choice: ")
        
        if choice == "0":
            print("\nThank you for using the Intermediate Python Cheat Sheet. Goodbye!")
            break
        elif choice == "1":
            display_file_handling()
        elif choice == "2":
            display_exception_handling()
        elif choice == "3":
            display_regex()
        elif choice == "4":
            display_decorators()
        elif choice == "5":
            display_virtual_environments()
        elif choice == "6":
            display_pip_management()
        elif choice == "7":
            display_datetime()
        elif choice == "8":
            display_oop()
        elif choice == "9":
            display_help()
        else:
            print("\nInvalid choice. Please try again.")

if __name__ == "__main__":
    main()
